name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          commit_message: "anime: updated recently watched list"
          feed_list: "https://myanimelist.net/rss.php?type=rw&u=unasareyou"
          item_exec: |
                    post.title = post.title.replace(/\s-\sTV/, '');
                    post.description = (arr =>
                      arr[0] == 0
                        ? 'Plan 2 Watch'
                        : (n =>
                            '█'.repeat(n) + '░'.repeat(12 - n)
                          )(~~( arr[0] * ( 12 / arr[1] )))
                      )(
                        post.description
                          .match(/(\d+)/g)
                          .map(n => +n)
                      );
          template: "$newline`$description` [$title]($url) <br />"
