name: Recent Anime
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs once a day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: RECENT-ANIME 
          commit_message: "anime: update recently watched list"
          feed_list: "https://myanimelist.net/rss.php?type=rw&u=xn--z7x"
          item_exec: |
                    post.title = (s => 
                        s.length < 27
                          ? s + ' '.repeat(27 - s.length)
                          : s.length > 24
                            ? s.substring(0, 24) + '...'
                            : s
                      )(
                        post.title.replace(/\s-\sTV/, '')
                      );
                    post.description = (arr =>
                      arr.length == 1
                        ? '░'.repeat(25) + `   ${arr[0]}/???`
                        : (n =>
                            '█'.repeat(n) + '░'.repeat(25 - n)
                          )(~~( arr[0] * ( 25 / arr[1] )))
                          + `   ${arr[0]}/${arr[1]}`
                      )(
                        post.description
                          .match(/(\d+)/g)
                          .map(n => +n)
                      );
          tag_post_pre_newline: true
          template: "$newline    $title  $description"
